//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Breeding
    {
        public int BreedingID { get; set; }
        public int BreedingSire_dogID { get; set; }
        public int BreedingDam_dogID { get; set; }
        public string BreedingVet { get; set; }
        public Nullable<int> HeatID { get; set; }
        public Nullable<System.DateTime> InseminationDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public string LastUpdateID { get; set; }
        public System.DateTime LastUpdateTimeStamp { get; set; }
    
        public virtual Females_Heat Females_Heat { get; set; }
    }
}
