//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Breeder
    {
        public int BreederID { get; set; }
        public string BreederName { get; set; }
        public string BreederAddress { get; set; }
        public string BreederCity { get; set; }
        public string BreederState { get; set; }
        public string BreederZip { get; set; }
        public string BreederEmail { get; set; }
        public string BreederKennel { get; set; }
        public string BreederWebSite { get; set; }
        public string BreederPhone { get; set; }
        public Nullable<bool> Active { get; set; }
        public string LastUpdateID { get; set; }
        public System.DateTime LastUpdateTimeStamp { get; set; }
    }
}
