//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary3
{
    using System;
    using System.Collections.Generic;
    
    public partial class DogSale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DogSale()
        {
            this.DogSalePayments = new HashSet<DogSalePayment>();
            this.DogSalesDocuments = new HashSet<DogSalesDocument>();
        }
    
        public int DogSalesID { get; set; }
        public int DogID { get; set; }
        public decimal SalesPrice { get; set; }
        public System.DateTime DateContractMailed { get; set; }
        public Nullable<System.DateTime> DogSaleDate { get; set; }
        public string DogSaleNotes { get; set; }
        public Nullable<bool> Active { get; set; }
        public string LastUpdateID { get; set; }
        public System.DateTime LastUpdateTimeStamp { get; set; }
    
        public virtual Dog Dog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DogSalePayment> DogSalePayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DogSalesDocument> DogSalesDocuments { get; set; }
    }
}
