//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbFFBEntities : DbContext
    {
        public dbFFBEntities()
            : base("name=dbFFBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Breeder> Breeders { get; set; }
        public virtual DbSet<Breeding> Breedings { get; set; }
        public virtual DbSet<Dog> Dogs { get; set; }
        public virtual DbSet<DogDocument> DogDocuments { get; set; }
        public virtual DbSet<DogOwner> DogOwners { get; set; }
        public virtual DbSet<DogPhoto> DogPhotoes { get; set; }
        public virtual DbSet<DogPhotoDocument> DogPhotoDocuments { get; set; }
        public virtual DbSet<DogSalePayment> DogSalePayments { get; set; }
        public virtual DbSet<DogSalePaymentDocument> DogSalePaymentDocuments { get; set; }
        public virtual DbSet<DogSale> DogSales { get; set; }
        public virtual DbSet<DogSalesDocument> DogSalesDocuments { get; set; }
        public virtual DbSet<DogWeight> DogWeights { get; set; }
        public virtual DbSet<DogWeightDocument> DogWeightDocuments { get; set; }
        public virtual DbSet<Females_Heat> Females_Heat { get; set; }
        public virtual DbSet<Litter> Litters { get; set; }
        public virtual DbSet<LitterDocument> LitterDocuments { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<OwnerDocument> OwnerDocuments { get; set; }
        public virtual DbSet<SettingT> SettingTs { get; set; }
        public virtual DbSet<StatusT> StatusTs { get; set; }
        public virtual DbSet<vw_activeFemales> vw_activeFemales { get; set; }
        public virtual DbSet<vw_activeMales> vw_activeMales { get; set; }
        public virtual DbSet<vw_cboSearchLitters> vw_cboSearchLitters { get; set; }
    }
}
