//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Litter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Litter()
        {
            this.LitterDocuments = new HashSet<LitterDocument>();
        }
    
        public int LitterID { get; set; }
        public string AKCLitter { get; set; }
        public int Sire_dogID { get; set; }
        public int Dam_dogID { get; set; }
        public int LitterFemales { get; set; }
        public int LitterMales { get; set; }
        public string DeliverVet { get; set; }
        public System.DateTime WhelpDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public string LastUpdateID { get; set; }
        public System.DateTime LastUpdateTimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LitterDocument> LitterDocuments { get; set; }
    }
}
